# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 13:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_kat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Kat',
        ),
    ]
