# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 12:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='username',
            new_name='user',
        ),
    ]
